name: charity_discount
description: Empowering charity.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+5

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0
  google_sign_in: ^4.0.6
  firebase_auth: ^0.14.0
  firebase_analytics: ^5.0.0
  cloud_firestore: ^0.12.9
  rxdart: ^0.22.1
  http: ^0.12.0
  flushbar: ^1.9.0
  shared_preferences: ^0.5.4
  easy_localization: ^1.3.1
  flutter_screenutil: ^0.6.0
  url_launcher: ^5.1.2
  gradient_text: ^1.0.2
  scoped_model: ^1.0.1
  timeline_list: ^0.0.5
  cached_network_image: ^2.0.0-rc
  intl: ^0.16.0
  firebase_remote_config: ^0.2.0
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.14.1
  iban_form_field: ^0.1.7
  flutter_html: ^0.11.0
  flutter_rating_bar: ^3.0.0
  flutter_facebook_login: ^3.0.0
  local_auth: ^0.6.0+1
  firebase_messaging: ^5.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  build_runner: ^1.6.8
  json_serializable: ^3.2.2

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/i18n/en-US.json
    - assets/i18n/ro-RO.json
    - assets/icons/
  fonts:
    - family: SocialIcons
      fonts:
        - asset: assets/fonts/SocialIcons.ttf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icons/icon.png
  adaptive_icon_background: '#ffffff'
