name: charity_discount
description: Empowering charity.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0
  google_sign_in: ^4.0.6
  firebase_auth: ^0.14.0
  firebase_analytics: ^5.0.0
  cloud_firestore: ^0.12.9
  rxdart: ^0.22.1
  http: ^0.12.0
  flushbar: ^1.8.2
  shared_preferences: ^0.5.3
  easy_localization: ^1.3.1
  flutter_screenutil: ^0.5.3
  url_launcher: ^5.1.2
  gradient_text: ^1.0.2
  scoped_model: ^1.0.1
  timeline_list: ^0.0.5
  flutter_html: ^0.10.4
  cached_network_image: ^1.1.1
  intl: ^0.15.8

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2
  build_runner: ^1.6.4
  json_serializable: ^3.1.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/i18n/en-US.json
    - assets/i18n/ro-RO.json
    - assets/icons/
  fonts:
    - family: SocialIcons
      fonts:
        - asset: assets/fonts/SocialIcons.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather.ttf

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icons/icon.png
