name: charity_discount
description: Empowering charity.
publish_to: none

version: 1.11.1+700

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  firebase_core: ^0.5.3
  google_sign_in: ^4.5.6
  firebase_auth: ^0.18.4
  firebase_analytics: ^6.3.0
  cloud_firestore: ^0.14.4
  rxdart: ^0.25.0
  http: ^0.12.2
  flushbar:
    git:
      url: https://github.com/AndreHaueisen/flushbar
      ref: master
  shared_preferences: ^0.5.12
  easy_localization: ^2.3.4-nullsafety.1
  flutter_screenutil: ^4.0.2+1
  url_launcher: ^5.7.10
  scoped_model: ^2.0.0-nullsafety.0
  timeline_list: ^0.0.5
  cached_network_image: ^2.5.0
  intl: ^0.16.1
  firebase_remote_config: ^0.4.3
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.19.2+1
  iban_form_field: ^0.2.1
  flutter_html: ^1.1.1
  flutter_rating_bar: ^4.0.0-nullsafety.0
  flutter_facebook_login: ^3.0.0
  local_auth: ^0.6.3
  firebase_messaging: '^8.0.0-dev.11'
  devicelocale: ^0.3.3
  device_info: ^2.0.0-nullsafety.1
  apple_sign_in: ^0.1.0
  flutter_signin_button: ^1.1.0
  firebase_storage: '^5.2.0'
  image_picker: ^0.6.7+17
  image_cropper: ^1.3.1
  carousel_slider: ^2.3.1
  json_annotation: ^3.1.1
  firebase_crashlytics: ^0.2.4
  substring_highlight: ^0.1.2
  fluttertoast: ^8.0.0-nullsafety.0
  firebase_dynamic_links: ^0.6.3
  share: ^0.6.5+4
  package_info: ^0.4.3+2
  charts_flutter: ^0.9.0
  timeline_tile: ^1.0.0
  get_it: ^6.0.0-nullsafety.1
  percent_indicator: ^2.1.9

dependency_overrides:
   intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  build_runner: ^1.10.2
  json_serializable: ^3.5.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/i18n/en-US.json
    - assets/i18n/ro-RO.json
    - assets/icons/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
    - family: SocialIcons
      fonts:
        - asset: assets/fonts/SocialIcons.ttf

flutter_icons:
  android: true
  ios: true
  image_path_android: assets/icons/icon.png
  image_path_ios: assets/icons/icon-ios.png
  adaptive_icon_foreground: assets/icons/logo-adaptive.png
  adaptive_icon_background: '#ffffff'
